### ISSUE TITLE
DB-first

### ISSUE THREAD

**Issue by chayaleA** [malbruk/wolf-practicum-2024#31]
אשמח להסבר על:
DB First - קודם יוצרים את ה-DB והטבלאות ידנית, ואחר כך מפעילים יצירה אוטומטית של המחלקות ב-C# אוטומטית.
בניתי DB בGoogle Cloud
ואני רוצה עכשיו להשתמש בה דרך C#.

**Comment by malbruk** [comment]
@chayaleA 

תראי את ההסבר בפרקטיקוד 4, זה אותו עיקרון.
את יוצרת את הטבלאות ב-DB שבענן (את יכולה להתחבר אליו מאפליקציה לוקלית, בהתאם לסוג ה-DB)
בפרויקט הדוטנט יש להתקין פקג' (Provider) מתאים לפי סוג ה-DB.
ולהריץ את פקודת ה-Scaffold
שימי לב שה-Connection String קצת שונה בין סוג ה-DB.

**Comment by chayaleA** [comment]
התקנתי  (Provider) מתאים-MySql.Data.EntityFrameworkCore

![image](https://github.com/malbruk/wolf-practicum-2024/assets/150287616/b0709258-7283-4dfb-9ef9-a9c1d83345a0)
שיניתי את הConnection string בהתאם:
 "ConnectionString": "Server=bj17trghjaebpxnenuoj-mysql.services.clever-cloud.com;Database=bj17trghjaebpxnenuoj;Uid=udfgh6pm38hbg80e;Pwd=SModcarPV7ygRi7facJM;Port=3306",
והרצתי את הפקודה הזאת:
Scaffold-DbContext "Server=bj17trghjaebpxnenuoj-mysql.services.clever-cloud.com;Database=bj17trghjaebpxnenuoj;Uid=udfgh6pm38hbg80e;Pwd=SModcarPV7ygRi7facJM;Port=3306;" MySql.Data.EntityFrameworkCore -OutputDir Models
להרצת הפקודה הנ"ל התקבלה שגיאה כזאת:
Scaffold-DbContext "Server=bj17trghjaebpxnenuoj-mysql.services.clever-cloud.com;Database=bj17trghjaebpxnenuoj;Uid=udfgh6pm38hbg80e;Pwd=SModcarPV7ygRi7facJM;Port=3306;" MySql.Data.EntityFrameworkCore -OutputDir Models
Build started...
Build succeeded.
System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=6.0.25.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at MySql.Data.EntityFrameworkCore.Design.Internal.MySQLDesignTimeServices.ConfigureDesignTimeServices(IServiceCollection serviceCollection)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureDesignTimeServices(Type designTimeServicesType, IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.ConfigureProviderServices(String provider, IServiceCollection services, Boolean throwOnError)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.CreateServiceCollection(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DesignTimeServicesBuilder.Build(String provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not load type 'Microsoft.EntityFrameworkCore.Storage.IRelationalTypeMapper' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=6.0.25.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
PM>

**Comment by chayaleA** [comment]
סליחה,
זה עובד לי מצוין🤩🤩, הייתי צריכה להריץ פקודה אחרת, ולהתקין MYSQL אחר,
תודה רבה בכל אופן

**Comment by chayaleA** [comment]
העלתי את הסרבר לענן והוא מתחבר למסד הנתונים שבענן, הקליינט כנ"ל,
אני צריכה לשנות כאן את ה Issuer וה Audience?
"Jwt": {
    "Issuer": "https://localhost:7074",
    "Audience": "https://localhost:7074",
    "Key": "This is a sample secret key - please don't use in production environment."
  }

**Comment by chayaleA** [comment]
עונה למי שתראה את זה - לגבי מה ששאלתי קודם, התשובה היא כן צריך לשנות כמובן!
